### ISSUE TITLE
Add CircularFloatingActionMenu for Android

### ISSUE THREAD

**Issue by leocaseiro** [DeviantJS/nativescript-circle-menu#1]
Hi, thanks for this nice plugin!

I believe the similar Android module could be the  [CircularFloatingActionMenu](https://github.com/oguzbilgener/CircularFloatingActionMenu)

**Comment by joshwiens** [comment]
For reference, @NathanWalker and I opted to do these because we are both a fan or Ramotion's work and give the original offerings are all pods, the plugin implementation for NativeScript is actually pretty easy.

As to your specific request, the honest answer is neither of us is going to have time ( we haven't even had time to convert the rest of the Ramotion pods ). 

That said, Nathan has a great plugin seed ( which this was generated from ) [here](https://github.com/NathanWalker/nativescript-plugin-seed) which should enable you to take pretty much anything that outputs a pod and import it into an {N} plugin.

{N} also has a slack channel with a great community should you opt to try and create a plugin and have questions. You can request an invite to slack [here](http://developer.telerik.com/wp-login.php?action=slack-invitation)

**Comment by leocaseiro** [comment]
np, thanks for your reply. I'll have a look on that.
